package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.model.Instrutor;
import fatec.poo.model.Pessoa;
import fatec.poo.control.DaoInstrutor;
import fatec.poo.control.DaoPessoa;
import javax.swing.JOptionPane;
/**
 *
 * @author Arex de Barros
 */
public class GUIInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GUIinstrutor
     */
    public GUIInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCPF = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labSexo = new javax.swing.JLabel();
        labEnd = new javax.swing.JLabel();
        labBairro = new javax.swing.JLabel();
        labCidade = new javax.swing.JLabel();
        labRG = new javax.swing.JLabel();
        labForm = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        labNum = new javax.swing.JLabel();
        labEstado = new javax.swing.JLabel();
        labDatNas = new javax.swing.JLabel();
        labEstCiv = new javax.swing.JLabel();
        labCEP = new javax.swing.JLabel();
        labTelRes = new javax.swing.JLabel();
        labCel = new javax.swing.JLabel();
        labAreaAtu = new javax.swing.JLabel();
        cboxSexo = new javax.swing.JComboBox<>();
        cboxEstado = new javax.swing.JComboBox<>();
        cboxEstCiv = new javax.swing.JComboBox<>();
        ftfCPF = new javax.swing.JFormattedTextField();
        ftfCEP = new javax.swing.JFormattedTextField();
        ftfTelRes = new javax.swing.JFormattedTextField();
        ftfCel = new javax.swing.JFormattedTextField();
        ftfDatNas = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtfNome = new javax.swing.JTextField();
        txtfEnd = new javax.swing.JTextField();
        txtfBairro = new javax.swing.JTextField();
        txtfCidade = new javax.swing.JTextField();
        txtfForm = new javax.swing.JTextField();
        txtfEmail = new javax.swing.JTextField();
        txtfNum = new javax.swing.JTextField();
        txtfAreaAtu = new javax.swing.JTextField();
        ftfRG = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Instrutor");
        setSize(new java.awt.Dimension(3, 3));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labCPF.setText("CPF");

        labNome.setText("Nome");

        labSexo.setText("Sexo");

        labEnd.setText("Endereço");

        labBairro.setText("Bairro");

        labCidade.setText("Cidade");

        labRG.setText("RG");

        labForm.setText("Formação");

        labEmail.setText("Email");

        labNum.setText("N°");

        labEstado.setText("Estado");

        labDatNas.setText("Data de Nascimento");

        labEstCiv.setText("Estado Civil");

        labCEP.setText("CEP");

        labTelRes.setText("Tel. Res.");

        labCel.setText("Celular");

        labAreaAtu.setText("Área de Atuação");

        cboxSexo.setMaximumRowCount(9);
        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cboxSexo.setEnabled(false);

        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas ", "Amapá ", "Amazonas ", "Bahia ", "Ceará ", "Distrito Federal ", "Espírito Santo ", "Goiás ", "Maranhão", "Mato Grosso ", "Mato Grosso do Sul", "Minas Gerais ", "Pará ", "Paraíba ", "Paraná", "Pernambuco ", "Piauí", "Rio de Janeiro", "Rio Grande do Norte ", "Rio Grande do Sul", "Rondônia", "Roraima ", "Santa Catarina ", "São Paulo", "Sergipe", "Tocantins" }));
        cboxEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboxEstado.setEnabled(false);
        cboxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEstadoActionPerformed(evt);
            }
        });

        cboxEstCiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Viuvo(a)", "Divorciado(a)" }));
        cboxEstCiv.setEnabled(false);

        try {
            ftfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCPFActionPerformed(evt);
            }
        });

        try {
            ftfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCEP.setEnabled(false);
        ftfCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCEPActionPerformed(evt);
            }
        });

        try {
            ftfTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelRes.setEnabled(false);
        ftfTelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfTelResActionPerformed(evt);
            }
        });

        try {
            ftfCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCel.setEnabled(false);
        ftfCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCelActionPerformed(evt);
            }
        });

        try {
            ftfDatNas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDatNas.setToolTipText("");
        ftfDatNas.setEnabled(false);
        ftfDatNas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDatNasActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtfNome.setEnabled(false);

        txtfEnd.setEnabled(false);
        txtfEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEndActionPerformed(evt);
            }
        });

        txtfBairro.setEnabled(false);

        txtfCidade.setEnabled(false);
        txtfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCidadeActionPerformed(evt);
            }
        });

        txtfForm.setEnabled(false);
        txtfForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFormActionPerformed(evt);
            }
        });

        txtfEmail.setEnabled(false);

        txtfNum.setEnabled(false);
        txtfNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNumActionPerformed(evt);
            }
        });

        txtfAreaAtu.setEnabled(false);

        try {
            ftfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfRG.setEnabled(false);
        ftfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfRGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnInserir)
                                .addGap(37, 37, 37)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labEstCiv)
                                        .addGap(108, 108, 108))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labTelRes)
                                            .addComponent(labCEP))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ftfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ftfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labCel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftfCel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labEmail)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfEmail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labForm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfForm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(labAreaAtu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfAreaAtu))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(147, 147, 147)
                                        .addComponent(labDatNas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labSexo)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labBairro)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labEnd)
                                                .addGap(29, 29, 29)
                                                .addComponent(txtfEnd)))
                                        .addGap(28, 28, 28)
                                        .addComponent(labNum)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtfNum, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labCPF)
                                        .addGap(18, 18, 18)
                                        .addComponent(ftfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labEstado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ftfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxEstCiv, 0, 1, Short.MAX_VALUE)
                                    .addComponent(ftfDatNas))))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCPF)
                    .addComponent(ftfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfDatNas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDatNas))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSexo)
                    .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labEstCiv)
                    .addComponent(cboxEstCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEnd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labNum)
                                .addComponent(txtfNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labBairro)
                            .addComponent(txtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCidade)
                            .addComponent(txtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labEstado))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labRG)
                            .addComponent(ftfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfAreaAtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labAreaAtu)
                                    .addComponent(labForm))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labEmail))
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(btnInserir)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSair)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCEP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labTelRes)
                            .addComponent(ftfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCel))))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCPFActionPerformed

    private void ftfCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCEPActionPerformed

    private void ftfTelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfTelResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfTelResActionPerformed

    private void ftfCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfCelActionPerformed

    private void ftfDatNasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfDatNasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfDatNasActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        pessoa = new Pessoa(cpf, txtfNome.getText());
        instrutor = new Instrutor(cpf, txtfNome.getText());
        
        pessoa.setCPF(cpf);
        pessoa.setNome(txtfNome.getText());
        pessoa.setDataNasc(ftfDatNas.getText());
        pessoa.setEndereco(txtfEnd.getText());
        pessoa.setNumero(Integer.parseInt(txtfNum.getText()));
        pessoa.setBairro(txtfBairro.getText());
        pessoa.setCidade(txtfCidade.getText());
        pessoa.setEstado(cboxEstado.getSelectedItem().toString());
        pessoa.setCEP(ftfCEP.getText().replaceAll("[-]", ""));
        pessoa.setTelefone(ftfTelRes.getText().replaceAll("[(,),-]", ""));
        pessoa.setCelular(ftfCel.getText().replaceAll("[(,),-]", ""));
        pessoa.setSexo(cboxSexo.getSelectedItem().toString());
        pessoa.setEstadoCivil(cboxEstCiv.getSelectedItem().toString());
        pessoa.setRG(ftfRG.getText().replaceAll("[.,-]", ""));
        pessoa.setEmail(txtfEmail.getText());
           
        instrutor.setCPF(cpf);
        instrutor.setFormacao(txtfForm.getText());
        instrutor.setAreaAtuacao(txtfAreaAtu.getText());
           
        
        daoPessoa.inserir(pessoa);
        daoInstrutor.inserir(instrutor);
        
        ftfCPF.setText("");
        txtfNome.setText("");
        cboxEstCiv.setSelectedIndex(0x0);
        txtfEnd.setText("");
        ftfDatNas.setText("");
        cboxSexo.setSelectedIndex(0x0);
        txtfNum.setText("");
        txtfBairro.setText("");
        ftfCEP.setText("");
        txtfCidade.setText("");
        cboxEstado.setSelectedIndex(0x0);
        ftfRG.setText("");
        txtfForm.setText("");
        txtfEmail.setText("");
        ftfTelRes.setText("");
        ftfCel.setText("");
        txtfAreaAtu.setText("");
        
        ftfCPF.setEnabled(true);
        txtfNome.setEnabled(false);
        cboxEstCiv.setEnabled(false);
        txtfEnd.setEnabled(false);
        ftfDatNas.setEnabled(false);
        cboxSexo.setEnabled(false);
        txtfNum.setEnabled(false);
        txtfBairro.setEnabled(false);
        ftfCEP.setEnabled(false);
        txtfCidade.setEnabled(false);
        cboxEstado.setEnabled(false);
        ftfRG.setEnabled(false);
        txtfForm.setEnabled(false);
        txtfEmail.setEnabled(false);
        ftfTelRes.setEnabled(false);
        ftfCel.setEnabled(false);
        txtfAreaAtu.setEnabled(false);
        ftfCPF.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void cboxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEstadoActionPerformed

    private void txtfEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEndActionPerformed

    private void txtfFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFormActionPerformed

    private void txtfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCidadeActionPerformed

    private void txtfNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNumActionPerformed

    private void ftfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfRGActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("","");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoInstrutor = new DaoInstrutor(conexao.conectar());
        daoPessoa = new DaoPessoa(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        cpf = ftfCPF.getText().replaceAll("[.,-]", "");
        
        if(Pessoa.validarCPF(cpf) == true){
            pessoa = null;
            instrutor = null;
            pessoa = daoPessoa.consultar(cpf);
            instrutor = daoInstrutor.consultar(cpf);
        
            if(instrutor == null){
                btnConsultar.setEnabled(false);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnInserir.setEnabled(true);
            }
            else{
                txtfNome.setText(pessoa.getNome());
                cboxEstCiv.setSelectedItem(pessoa.getEstadoCivil());
                txtfEnd.setText(pessoa.getEndereco());
                ftfDatNas.setText(pessoa.getDataNasc().replaceAll("[/]", ""));
                cboxSexo.setSelectedItem(pessoa.getSexo());
                txtfNum.setText(Integer.toString(pessoa.getNumero()));
                txtfBairro.setText(pessoa.getBairro());
                ftfCEP.setText(pessoa.getCEP());
                txtfCidade.setText(pessoa.getCidade());
                cboxEstado.setSelectedItem(pessoa.getEstado());
                ftfRG.setText(pessoa.getRG());
                txtfForm.setText(instrutor.getFormacao());
                txtfEmail.setText(pessoa.getEmail());
                ftfTelRes.setText(pessoa.getTelefone());
                ftfCel.setText(pessoa.getCelular());
                txtfAreaAtu.setText(instrutor.getAreaAtuacao());
             
                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
            
            ftfCPF.setEnabled(false);
                txtfNome.setEnabled(true);
                cboxEstCiv.setEnabled(true);
                txtfEnd.setEnabled(true);
                ftfDatNas.setEnabled(true);
                cboxSexo.setEnabled(true);
                txtfNum.setEnabled(true);
                txtfBairro.setEnabled(true);
                ftfCEP.setEnabled(true);
                txtfCidade.setEnabled(true);
                cboxEstado.setEnabled(true);
                ftfRG.setEnabled(true);
                txtfForm.setEnabled(true);
                txtfEmail.setEnabled(true);
                ftfTelRes.setEnabled(true);
                ftfCel.setEnabled(true);
                txtfAreaAtu.setEnabled(true);
                txtfNome.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(null, "CPF inserido não é válido.");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){//Sim
           pessoa.setCPF(cpf);
           pessoa.setNome(txtfNome.getText());
           pessoa.setDataNasc(ftfDatNas.getText());
           pessoa.setEndereco(txtfEnd.getText());
           pessoa.setNumero(Integer.parseInt(txtfNum.getText()));
           pessoa.setBairro(txtfBairro.getText());
           pessoa.setCidade(txtfCidade.getText());
           pessoa.setEstado(cboxEstado.getSelectedItem().toString());
           pessoa.setCEP(ftfCEP.getText().replaceAll("[-]", ""));
           pessoa.setTelefone(ftfTelRes.getText().replaceAll("[(,),-]", ""));
           pessoa.setCelular(ftfCel.getText().replaceAll("[(,),-]", ""));
           pessoa.setSexo(cboxSexo.getSelectedItem().toString());
           pessoa.setEstadoCivil(cboxEstCiv.getSelectedItem().toString());
           pessoa.setRG(ftfRG.getText().replaceAll("[.,-]", ""));
           pessoa.setEmail(txtfEmail.getText());
           
           instrutor.setCPF(cpf);
           instrutor.setFormacao(txtfForm.getText());
           instrutor.setAreaAtuacao(txtfAreaAtu.getText());
           
           daoPessoa.alterar(pessoa);
           daoInstrutor.alterar(instrutor);
        }
        
        ftfCPF.setText("");
        txtfNome.setText("");
        cboxEstCiv.setSelectedIndex(0x0);
        txtfEnd.setText("");
        ftfDatNas.setText("");
        cboxSexo.setSelectedIndex(0x0);
        txtfNum.setText("");
        txtfBairro.setText("");
        ftfCEP.setText("");
        txtfCidade.setText("");
        cboxEstado.setSelectedIndex(0x0);
        ftfRG.setText("");
        txtfForm.setText("");
        txtfEmail.setText("");
        ftfTelRes.setText("");
        ftfCel.setText("");
        txtfAreaAtu.setText("");
             
        ftfCPF.setEnabled(true);
        txtfNome.setEnabled(false);
        cboxEstCiv.setEnabled(false);
        txtfEnd.setEnabled(false);
        ftfDatNas.setEnabled(false);
        cboxSexo.setEnabled(false);
        txtfNum.setEnabled(false);
        txtfBairro.setEnabled(false);
        ftfCEP.setEnabled(false);
        txtfCidade.setEnabled(false);
        cboxEstado.setEnabled(false);
        ftfRG.setEnabled(false);
        txtfForm.setEnabled(false);
        txtfEmail.setEnabled(false);
        ftfTelRes.setEnabled(false);
        ftfCel.setEnabled(false);
        txtfAreaAtu.setEnabled(false);
        ftfCPF.requestFocus();
            
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            daoInstrutor.excluir(instrutor);
            daoPessoa.excluir(pessoa);
        }
        
        ftfCPF.setText("");
        txtfNome.setText("");
        cboxEstCiv.setSelectedIndex(0x0);
        txtfEnd.setText("");
        ftfDatNas.setText("");
        cboxSexo.setSelectedIndex(0x0);
        txtfNum.setText("");
        txtfBairro.setText("");
        ftfCEP.setText("");
        txtfCidade.setText("");
        cboxEstado.setSelectedIndex(0x0);
        ftfRG.setText("");
        txtfForm.setText("");
        txtfEmail.setText("");
        ftfTelRes.setText("");
        ftfCel.setText("");
        txtfAreaAtu.setText("");
             
        ftfCPF.setEnabled(true);
        txtfNome.setEnabled(false);
        cboxEstCiv.setEnabled(false);
        txtfEnd.setEnabled(false);
        ftfDatNas.setEnabled(false);
        cboxSexo.setEnabled(false);
        txtfNum.setEnabled(false);
        txtfBairro.setEnabled(false);
        ftfCEP.setEnabled(false);
        txtfCidade.setEnabled(false);
        cboxEstado.setEnabled(false);
        ftfRG.setEnabled(false);
        txtfForm.setEnabled(false);
        txtfEmail.setEnabled(false);
        ftfTelRes.setEnabled(false);
        ftfCel.setEnabled(false);
        txtfAreaAtu.setEnabled(false);
        ftfCPF.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cboxEstCiv;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JComboBox<String> cboxSexo;
    private javax.swing.JFormattedTextField ftfCEP;
    private javax.swing.JFormattedTextField ftfCPF;
    private javax.swing.JFormattedTextField ftfCel;
    private javax.swing.JFormattedTextField ftfDatNas;
    private javax.swing.JFormattedTextField ftfRG;
    private javax.swing.JFormattedTextField ftfTelRes;
    private javax.swing.JLabel labAreaAtu;
    private javax.swing.JLabel labBairro;
    private javax.swing.JLabel labCEP;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labCel;
    private javax.swing.JLabel labCidade;
    private javax.swing.JLabel labDatNas;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labEnd;
    private javax.swing.JLabel labEstCiv;
    private javax.swing.JLabel labEstado;
    private javax.swing.JLabel labForm;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labNum;
    private javax.swing.JLabel labRG;
    private javax.swing.JLabel labSexo;
    private javax.swing.JLabel labTelRes;
    private javax.swing.JTextField txtfAreaAtu;
    private javax.swing.JTextField txtfBairro;
    private javax.swing.JTextField txtfCidade;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfEnd;
    private javax.swing.JTextField txtfForm;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfNum;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao;
    private DaoInstrutor daoInstrutor;
    private DaoPessoa daoPessoa;
    private Pessoa pessoa;
    private Instrutor instrutor;
    private String cpf;
}
