/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author Gorom
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        mbarPrincipal = new javax.swing.JMenuBar();
        menCadastros = new javax.swing.JMenu();
        mitnCurso = new javax.swing.JMenuItem();
        mitnTurma = new javax.swing.JMenuItem();
        mitnInstrutor = new javax.swing.JMenuItem();
        mitnAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mitnSair = new javax.swing.JMenuItem();
        menOperacoes = new javax.swing.JMenu();
        mitnAlocInstrutor = new javax.swing.JMenuItem();
        mitnEfetMatricula = new javax.swing.JMenuItem();

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");

        menCadastros.setText("Cadastros");

        mitnCurso.setText("Curso");
        mitnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnCursoActionPerformed(evt);
            }
        });
        menCadastros.add(mitnCurso);

        mitnTurma.setText("Turma");
        mitnTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnTurmaActionPerformed(evt);
            }
        });
        menCadastros.add(mitnTurma);

        mitnInstrutor.setText("Instrutor");
        mitnInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnInstrutorActionPerformed(evt);
            }
        });
        menCadastros.add(mitnInstrutor);

        mitnAluno.setText("Aluno");
        mitnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnAlunoActionPerformed(evt);
            }
        });
        menCadastros.add(mitnAluno);
        menCadastros.add(jSeparator1);

        mitnSair.setText("Sair");
        mitnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitnSairActionPerformed(evt);
            }
        });
        menCadastros.add(mitnSair);

        mbarPrincipal.add(menCadastros);

        menOperacoes.setText("Operações");

        mitnAlocInstrutor.setText("Alocar instrutor");
        menOperacoes.add(mitnAlocInstrutor);

        mitnEfetMatricula.setText("Efetuar matrícula");
        menOperacoes.add(mitnEfetMatricula);

        mbarPrincipal.add(menOperacoes);

        setJMenuBar(mbarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnCursoActionPerformed
        new GUICurso().setVisible(true);
    }//GEN-LAST:event_mitnCursoActionPerformed

    private void mitnTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnTurmaActionPerformed
        new GUITurma().setVisible(true);
    }//GEN-LAST:event_mitnTurmaActionPerformed

    private void mitnInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnInstrutorActionPerformed
        new GUIInstrutor().setVisible(true);
    }//GEN-LAST:event_mitnInstrutorActionPerformed

    private void mitnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnAlunoActionPerformed
        new GUIAluno().setVisible(true);
    }//GEN-LAST:event_mitnAlunoActionPerformed

    private void mitnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitnSairActionPerformed
        dispose();
    }//GEN-LAST:event_mitnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mbarPrincipal;
    private javax.swing.JMenu menCadastros;
    private javax.swing.JMenu menOperacoes;
    private javax.swing.JMenuItem mitnAlocInstrutor;
    private javax.swing.JMenuItem mitnAluno;
    private javax.swing.JMenuItem mitnCurso;
    private javax.swing.JMenuItem mitnEfetMatricula;
    private javax.swing.JMenuItem mitnInstrutor;
    private javax.swing.JMenuItem mitnSair;
    private javax.swing.JMenuItem mitnTurma;
    // End of variables declaration//GEN-END:variables
}
